import sys
if __name__ == "__main__":    
    sample_list1 = [0,342,210,350,314,354,152,212,445,274,342,422,443,325,275,317,315,415,352,245,210,245,350,315,270,320,320,352,331,220,153,195]
    sample_list2 = [0,332,270,310,414,324,252,312,345,374,312,412,453,315,270,312,275,345,412,345,410,315,410,275,320,400,350,312,371,210,150,215]
    print "HTTP/1.0 200 OK"
    print "Content-Type: text/html"
    print ""
    print "<html>"   
    print "<style type=\"text/css\">"
    print "    #mychart1 {"
    print "    width: 1340px;"
    print "    height: 400px;"
    print "}"
    print "td{"
    print "    border:1px solid #555;"
    print "    color:#e9e9e9;"
    print "    FONT-SIZE:16pt;"
    print "}"
    print "    .words {  "
    print "        color: #e9e9e9;  "
    print "        border: solid 1px #555; " 
    print "       background: #afafaf;  "
    print "    }"
    print "</style>"
    print "<script src=\"http://yui.yahooapis.com/3.10.1/build/yui/yui-min.js\"></script>"
    print "<script language=\"javascript\" type=\"text/javascript\"> "
    print "YUI().use(\'charts\', function (Y) "
    print "{ "
    print "    var myDataValues1 = [ "

    for vari in range(1,32):
        response1 = "%d" % (sample_list1[vari])
        response2 = "%d" % (sample_list2[vari])
        #cmd = "select count(data) from user where year = %d and mon = %d % (year,vari)
        #conn = httplib.HTTPConnection("localhost","8000")
       # conn.request("GET","/cgi-bin/database.py?"+cmd)
        #response1 = conn.getresponse() 
        stri = "%d" % (vari)
        if vari == 31:
            print "        {category:\""+stri+"\", action:"+response1+", statistic:"+response2+"}"
        else :
            print "        {category:\""+stri+"\", action:"+response1+", statistic:"+response2+"},"

   # print "        {category:\"5/1/2010\", action:2000, statistic:3700 }," 
   # print "        {category:\"5/2/2010\", action:50, statistic:9100}, "
   # print "        {category:\"5/3/2010\", action:400, statistic:1100}, "
   # print "        {category:\"5/4/2010\", action:200, statistic:1900}, "
   # print "        {category:\"5/5/2010\", action:5000, statistic:5000}"
    print "    ]; "
    print "    var mychart1 = new Y.Chart({"
    print "                        dataProvider:myDataValues1, "
    print "                        render:\"#mychart1\","
    print "                        horizontalGridlines: {"
    print "                            styles: {"
    print "                                line: {"
    print "                                    color: \"#dad8c9\""
    print "                                }"
    print "                            }"
    print "                        },"
    print "                        verticalGridlines: {"
    print "                            styles: {"
    print "                                line: {"
    print "                                    color: \"#dad8c9\""
    print "                                }"
    print "                            }"
    print "                        }"
    print "                    });"
    print "});"
    print "</script> "
    print "<body  >"
    print "<div class=\"words\" >"
    print "<table width=\"1360\" height=\"240\" border=\"1\">"
    print " <tr>"
    print "<td width=\"220\" align=\"center\" valign=\"middle\">&nbsp;</td>"
    print "    <td width=\"264\" align=\"center\" valign=\"middle\">Mean</td>"
    print "    <td width=\"247\" align=\"center\" valign=\"middle\">Maximum</td>"
    print "    <td width=\"238\" align=\"center\" valign=\"middle\">Score</td>"
    print "  </tr>"
    print "  <tr>"
    print "    <td align=\"center\" valign=\"middle\">Action Frequency</td>"
    print "    <td align=\"center\" valign=\"middle\">61/54</td>"
    print "    <td align=\"center\" valign=\"middle\">121/162</td>"
    print "    <td align=\"center\" valign=\"middle\">Fair</td>"
    print "  </tr>"
    print "  <tr>"
    print "    <td align=\"center\" valign=\"middle\">Action Strong</td>"
    print "    <td align=\"center\" valign=\"middle\">72/68</td>"
    print "    <td align=\"center\" valign=\"middle\">152/160</td>"
    print "    <td align=\"center\" valign=\"middle\">Good</td>"
    print "  </tr>"
    print "  <tr>"
    print "    <td align=\"center\" valign=\"middle\">Activity Times</td>"
    print "    <td align=\"center\" valign=\"middle\">124/117</td>"
    print "    <td align=\"center\" valign=\"middle\">362/321</td>"
    print "    <td align=\"center\" valign=\"middle\">Normal</td>"
    print "  </tr>"
    print "  <tr>"
    print "    <td align=\"center\" valign=\"middle\">Health Condition</td>"
    print "    <td colspan=\"2\" align=\"center\" valign=\"middle\">&nbsp;</td>"
    print "    <td align=\"center\" valign=\"middle\"><b><font color=\"green\" >Good</font></b></td>"
    print "  </tr>"
    print "</table>"
  #  print "<p>Action Frequency: Fair</p>"
  #  print "<p>Action Strongth: Good</p>"
  #  print "<p>Activity Times:    Normal</p><br><p><b>Health Condition: <font color=\"green\" >Good</front></b></p>"
    print"</div>"
    print "<p><div  class=\"graph\"  id=\"mychart1\"></div></p>"
    print "</body>"
    print "</html>"