import sys
import httplib
import time
if __name__ == "__main__":    
    print "HTTP/1.0 200 OK"
    print "Content-Type: text/html"
    print ""
    print "<html>"     
    print "<style type=\"text/css\">"
    print "    body {  "
    print "        color: #fcfcfc;  "
    print "    }"
    print "</style>"
    print "<body>"
    print "<table width=\"1360\" border=\"0\">"
    print "  <tr>"
    print "    <td height=\"179\" colspan=\"3\" align=\"center\" valign=\"middle\" bgcolor=\"#FF0000\"><form id=\"form1\" name=\"form1\" method=\"post\" >"
    print "      <h1>TurenLeft</h1>"
    print "    </form></td>"
    print "    <td colspan=\"4\" align=\"center\" valign=\"middle\" bgcolor=\"#FFCC00\"><h1><strong>Turn Right</strong></h1></td>"
    print "  </tr>"
    print "  <tr>"
    print "    <td width=\"224\" height=\"109\" align=\"center\" valign=\"middle\" bgcolor=\"#000099\"><h1><strong>Ctrl</strong></h1></td>"
    print "    <td colspan=\"2\" align=\"center\" valign=\"middle\" bgcolor=\"#00CCFF\"><h1><strong>Alt</strong></h1></td>"
    print "    <td colspan=\"2\" align=\"center\" valign=\"middle\" bgcolor=\"#00FF33\"><h1><strong>Middle Button</strong></h1></td>"
    print "    <td width=\"138\" align=\"center\" valign=\"middle\" bgcolor=\"#339966\"><h1><strong>Space</strong></h1></td>"
    print "    <td width=\"139\" align=\"center\" valign=\"middle\" bgcolor=\"#6633CC\"><h1><strong>Shitf</strong></h1></td>"
    print "  </tr>"
    print "  <tr>"
    print "    <td height=\"164\" align=\"center\" valign=\"middle\" bgcolor=\"#CCCC99\"><h1><strong>Left Page</strong></h1></td>"
    print "    <td width=\"163\" align=\"center\" valign=\"middle\" bgcolor=\"#CCCC00\"><h1><strong>Right Page</strong></h1></td>"
    print "    <td colspan=\"2\" align=\"center\" valign=\"middle\" bgcolor=\"#999966\"><h1><strong>Up</strong></h1></td>"
    print "    <td width=\"109\" align=\"center\" valign=\"middle\" bgcolor=\"#FFCCCC\"><h1><strong>Down</strong></h1></td>"
    print "    <td align=\"center\" valign=\"middle\" bgcolor=\"#FFCC99\"><h1><strong>Enter</strong></h1></td>"
    print "    <td align=\"center\" valign=\"middle\" bgcolor=\"#FFFF99\"><h1><strong>Back</strong></h1></td>"
    print "  </tr>"
    print "  <tr>"
    print "    <td height=\"200\" colspan=\"7\" align=\"center\" valign=\"middle\" bgcolor=\"#999999\"><h1><strong>Generate</strong></h1></td>"
    print "  </tr>"
    print "</table>"
    print "</body>"
    print "</html>"